### ISSUE TITLE
Please consider adding x86 macos binary link to README

### ISSUE THREAD

**Issue by fogus** [aapen/aapen#1]
In the README you mention the use of the macos binary for aarch64 but that does not work for my machine. Instead, I changed the binary link to point to zig-macos-x86_64-0.12.0-dev.494+a8d2ed806 downloaded it and it worked like a charm. Others in my predicament would benefit from a mention.

https://github.com/aapen/aapen/blob/6a46f573645b3a4de3f3ae0347dcb94860c5eacf/README.md?plain=1#L48

Thanks!
:f

**Comment by mtnygard** [comment]
Thank you for filing Issue #1. 😄 

I added the link in 5a95160379f8a1d63a46dc906be88b9152a6774f
